name: Continuous integration

on:
  push:
    branches:
    - main
    - feature/*

#permissions:
#  contents: read

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: virtualenv
      run: make venv

    - name: Install dependencies
      run: make install

    - name: Run model test
      run: make model-test

    - name: Run api test
      run: make api-test

    - name: display message
      run: echo "All tests passed"