name: Continuous integration

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: create env
      run: make venv

    - name: activate env
      run: source .venv/bin/activate

    - name: Install dependencies
      run: make install

    - name: Run model test
      run: make model-test

    - name: Run api test
      run: make api-test

    - name: display message
      run: echo "All tests passed"